id: P2B8D440B
initial_creation_type: input
source_metadata:
  title: Ngakchang Shakya Zangpo Series
  language: en
  description: 'Texts related to the tertön Ngakchang Shakya Zangpo (sngags ''chang
    shākya bzang po, b. 15th century), who is famous for having opened up the ''hidden
    land'' of Yolmo:'
  volume:
    794152c8e59d42948ec57b4575662b4a:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: History
created_at: '2022-03-01T00:59:21.983864'
last_modified_at: '2022-03-01T00:59:21.983870'
